[package]
name = "neuronfun"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
plotters = "0.3.7"
rand = "0.8.5"
rand_distr = "0.4.3"

[[bin]]
name="retexter"

[[bin]]
name="rgbvenner"